input:
  type: csv
  properties:
    path: input.csv
    target_column: content
    separator: "\t"

pipeline:
  - type: split
    method: chunk
    name: chunk_faq
    parameters:
      size: 500

  - type: generation
    method: llm
    parameters:
      provider: openrouter
      model: openai/gpt-3.5-turbo
      template: |
        Generate a concise summary of the following text.
        
        Text: {chunk_faq}
        
        Summary:
      temperature: 0.7

output:
  type: csv
  properties:
    path: output.csv
    separator: "\t"